In [137]:
import pandas as pd
import numpy as np

In [156]:
data = pd.read_csv('dataset_V4.csv')
categorical_var = [
 'HUQ010',
 'HUQ050',
 'HUQ060',
 'DPQ010',
 'DPQ030',
 'DPQ040',
 'DPQ050','DPQ080']
numerical_var = [
 'PAD680',
 'HUD080',
 'HSQ470',
 'HSQ490',
 'HSQ493',
 'HSQ496',
 'MCQ180A',
 'MCQ180B',
 'MCQ180C',
 'MCQ180D',
 'MCQ180E','MCQ180F','MCQ180K']

In [157]:
dataset = data[['PFQ061B','PFQ061C','PFQ061H']+numerical_var+categorical_var]

In [158]:
correlation = dataset.corr().iloc[[0,1,2]].drop(['PFQ061B','PFQ061C','PFQ061H'],axis=1)

In [159]:
for column in numerical_var:
    dataset[column].replace(np.nan,dataset[column].mean(),inplace = True)

In [160]:
dataset.head()

,PFQ061B,PFQ061C,PFQ061H,PAD680,HUD080,HSQ470,HSQ490,HSQ493,HSQ496,MCQ180A,...,MCQ180F,MCQ180K,HUQ010,HUQ050,HUQ060,DPQ010,DPQ030,DPQ040,DPQ050,DPQ080
0,NaN,NaN,NaN,383.78582,1.451001,3.438531,1.835656,2.972137,5.081421,50.460784,...,57.290179,34.595745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,383.78582,1.451001,3.438531,1.835656,2.972137,5.081421,50.460784,...,57.290179,34.595745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,383.78582,1.451001,3.438531,1.835656,2.972137,5.081421,50.460784,...,57.290179,34.595745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,383.78582,1.451001,3.438531,1.835656,2.972137,5.081421,50.460784,...,57.290179,34.595745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,383.78582,1.451001,3.438531,1.835656,2.972137,5.081421,50.460784,...,57.290179,34.595745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [172]:
for column in categorical_var:
    dataset[column].replace(np.nan,float(dataset[column].mode()),inplace = True)

In [177]:
XY1 = dataset.drop(['PFQ061C','PFQ061H'],axis = 1).dropna(subset = ["PFQ061B"])
XY2 = dataset.drop (['PFQ061B','PFQ061H'], axis = 1).dropna(subset = ["PFQ061C"])
XY3 = dataset.drop (['PFQ061B','PFQ061C'], axis = 1).dropna(subset = ["PFQ061H"])

In [ ]:
XY1 = dataset.drop(['PFQ061C','PFQ061H'],axis = 1)
XY1.dropna(subset = ["PFQ061B"], inplace = True)

In [181]:
XY1.to_csv('PFQ061B.csv')
XY2.to_csv('PFQ061C.csv')
XY3.to_csv('PFQ061H.csv')

In [184]:
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score