In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("merged.csv")

In [3]:
data.head()

,SEQN,PAQ706,PAQ605,PAQ610,PAD615,PAQ620,PAQ625,PAD630,PAQ635,PAQ640,...,PFQ061Q,PFQ061R,PFQ061S,PFQ061T,PFQ063A,PFQ063B,PFQ063C,PFQ063D,PFQ063E,PFQ090
0,62161,,2,,,2,,,2,,...,5,5,1,5,28,,,,,2
1,62162,7,,,,,,,,,...,,,,,,,,,,
2,62163,,2,,,2,,,1,6,...,,,,,,,,,,
3,62164,,1,5,60,2,,,2,,...,,,,,,,,,,2
4,62165,,2,,,2,,,1,7,...,,,,,,,,,,

In [63]:
datafiltered = data[['SEQN','PFQ061B','PFQ061C','PFQ061H','PFQ054','PFQ020','PAQ665','PAQ670','PAD675','PAD680','PAQ706','PAQ710','PAQ715']]

datafiltered['PFQ061B'].replace(' ',np.nan, inplace=True)
for column in datafiltered:
    datafiltered[column].replace(' ',np.nan, inplace=True)

datafiltered['PFQ061B'].values[12][0]
datafiltered['PFQ061B'] = datafiltered['PFQ061B'].astype(float)

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [64]:
for column in datafiltered:
    datafiltered[column] = datafiltered[column].astype(float)

//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [66]:
datafiltered.corr()

,SEQN,PFQ061B,PFQ061C,PFQ061H,PFQ054,PFQ020,PAQ665,PAQ670,PAD675,PAD680,PAQ706,PAQ710,PAQ715
SEQN,1.000000,-0.007577,-0.008153,-0.017208,0.013593,-0.019075,0.004208,-0.014948,-0.005714,0.008518,-0.003496,0.013738,0.004419
PFQ061B,-0.007577,1.000000,0.520980,0.286552,0.149548,NaN,0.224789,-0.117383,-0.032143,0.076226,NaN,0.152039,0.135682
PFQ061C,-0.008153,0.520980,1.000000,0.298036,0.190539,NaN,0.195067,-0.025134,-0.072066,0.085989,NaN,0.096018,0.122150
PFQ061H,-0.017208,0.286552,0.298036,1.000000,-0.440766,NaN,0.186922,-0.028426,-0.036182,0.114201,NaN,0.130639,0.160819
PFQ054,0.013593,0.149548,0.190539,-0.440766,1.000000,NaN,-0.102985,-0.020224,0.037229,-0.028876,NaN,-0.048124,-0.065964
PFQ020,-0.019075,NaN,NaN,NaN,NaN,1.000000,-0.054455,0.019112,-0.018072,-0.101944,0.044276,-0.041727,-0.023328
PAQ665,0.004208,0.224789,0.195067,0.186922,-0.102985,-0.054455,1.000000,NaN,NaN,0.045773,NaN,0.083054,0.117533
PAQ670,-0.014948,-0.117383,-0.025134,-0.028426,-0.020224,0.019112,NaN,1.000000,-0.059850,-0.029946,NaN,-0.011444,0.059826
PAD675,-0.005714,-0.032143,-0.072066,-0.036182,0.037229,-0.018072,NaN,-0.059850,1.000000,0.007861,NaN,0.014670,-0.001745
PAD680,0.008518,0.076226,0.085989,0.114201,-0.028876,-0.101944,0.045773,-0.029946,0.007861,1.000000,NaN,0.207583,0.071226
PAQ706,-0.003496,NaN,NaN,NaN,NaN,0.044276,NaN,NaN,NaN,NaN,1.000000,-0.014717,0.001583
PAQ710,0.013738,0.152039,0.096018,0.130639,-0.048124,-0.041727,0.083054,-0.011444,0.014670,0.207583,-0.014717,1.000000,0.227755
PAQ715,0.004419,0.135682,0.122150,0.160819,-0.065964,-0.023328,0.117533,0.059826,-0.001745,0.071226,0.001583,0.227755,1.000000

In [83]:
PFQ061B_corr = datafiltered.corr()['PFQ061B'].drop(['SEQN','PFQ061B'])
max(PFQ061B_corr)

0.5209799452093363

In [67]:
testdata = datafiltered[['PFQ061B','PFQ061C']]

In [70]:
testdata.shape

(9135, 2)

In [71]:
testdata.dropna().shape

(1943, 2)

In [72]:
testdata.dropna().corr()

         PFQ061B  PFQ061C
PFQ061B  1.00000  0.52098
PFQ061C  0.52098  1.00000